apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: integration-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service@sha256:83a3cdcf4cb058c5dc3efeed4f5834857ecb22ef0a55e44de6d4fbc8b5dce03a
        name: container-image
        resources: {}
status: {}
