apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: integration-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service@sha256:b08b9302ce1f39e9e2322f1984f59d9bad0317f87b56523cf2a35acf95d69e8c
        name: container-image
        resources: {}
status: {}
