apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: integration-service
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service@sha256:7216591b6b66028d0935729d9ce42a0eba1eb594486d09018ccfeefcac36ab95
        name: container-image
        resources: {}
status: {}
