apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: integration-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: integration-service
    app.kubernetes.io/part-of: integration-service
  name: integration-serviceeagu
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: integration-service
    weight: 100
status: {}
