apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: integration-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: integration-service
    app.kubernetes.io/part-of: integration-service
  name: integration-service
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: integration-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: integration-service
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service@sha256:02554f848805eb8f053d57bd6b3306b2ad4e9e28c3c289af55349e1bb849b314
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
